# Generated by Django 3.0.4 on 2020-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignupCateringBoy',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='SignupCateringService',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='SignupCust',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='SignupMahalService',
            fields=[
            ],
        ),
    ]
