# Generated by Django 3.0.4 on 2020-04-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCustomer',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SignupCust',
        ),
        migrations.AlterModelOptions(
            name='signupcateringboy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='signupcateringservice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='signupmahalservice',
            options={'managed': False},
        ),
    ]
