# Generated by Django 3.0.4 on 2020-04-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MahalGallery',
            fields=[
            ],
        ),
    ]
